### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by Pigrecos** [stievie/UnicornPascal#2]
how can I conclude this library statically, not dynamically (.dll) as you made it in your project Sad Sam?
You need to insert too many DLLs to use the library

Thank you ;)

**Comment by stievie** [comment]
Sad Sam does not use Unicorn as emulator. It uses its own emulator (which is btw. very buggy and incomplete) writtren in Delphi. I'm afraid, you can't link it statically, since you can't link .lib files with Delphi. And even this wouldn't help much since you always have to include the dependencies of Unicorn (e.g. libglib, libintl etc.).
